language: minimal
dist: focal

before_install:
  - sudo unlink /usr/local/bin/packer
  - ci/provision.sh

script:
- sudo make dist

before_deploy:
  - cd dist && sudo ../ci/hashgen.sh && cd ..

deploy:
  provider: releases
  api_key:
    secure: <your deploy token>
  file_glob: true
  file: 
    - dist/*.zip
    - dist/*.zip.sha256
  skip_cleanup: true
  on:
    tags: true